/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
StudioLinkAudioProcessorEditor::StudioLinkAudioProcessorEditor (StudioLinkAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
}

StudioLinkAudioProcessorEditor::~StudioLinkAudioProcessorEditor()
{
}

//==============================================================================
void StudioLinkAudioProcessorEditor::paint (Graphics& g)
{

}

void StudioLinkAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
}
